description: O propósito desta stack é aprender a criar plugins, templates e a manipulá-los usando como tecnologia base o Java com framework Spring
name: java-spring
display-name: java-spring
picture: stack.png
category: backend # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/plugin/#category
compatibility: # Put a list of technologies compatible with the stack
  - java
  - spring
technologies: # Ref: https://docs.stackspot.com/docs/create-stacks/yaml-files/yaml/#technologies 
  - docker 
about: docs/about.md
use-cases:
  - title: Use Case Title
    content: docs/use-case.md
    stackfile: stackfiles/default.yaml